In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [49]:
A=[0,1,2,3]
gamma=0.9
gs=(5,5)
bs=[(1,2),(3,3)]
xsize=7
ysize=7
p=0.5

In [50]:
def tr(ix,iy,a):
    if(a==0):
        return ix-1,iy
    elif(a==1):
        return ix, iy-1
    elif(a==2):
        return ix, iy+1
    else:
        return ix+1,iy

In [51]:
def tp(ins,a,fis):
    ix,iy=ins
    fx,fy=fis
    ux,uy=tr(ix,iy,a)
    if(ix==0 and iy==0):
        if(fx==ux and fy==uy):
            return p
        else:
            return (1-p)
    if(ix==0 and iy==ysize-1):
        if(fx==ux and fy==uy):
            return p
        else:
            return (1-p)
    if(ix==xsize-1 and iy==0):
        if(fx==ux and fy==uy):
            return p
        else:
            return (1-p)
    if(ix==xsize-1 and iy==ysize-1):
        if(fx==ux and fy==uy):
            return p
        else:
            return (1-p)
    if(ix==0 or ix==xsize-1 or iy==0 or iy==ysize-1):
        if(fx==ux and fy==uy):
            return p
        else:
            return (1-p)/2
    else:
        if(fx==ux and fy==uy):
            return p
        else:
            return (1-p)/3

In [52]:
def rew(ins,a):
    ix,iy=ins
    gx,gy=gs
    fx,fy=tr(ix,iy,a)
    if(ix==gx and iy==gy):
        return 0
    for i in range(len(bs)):
        x0,y0=bs[i]
        if(x0==fx and y0==fy):
            return -50
    if(fx==0 or fx==xsize-1 or fy==0 or fy==ysize-1):
        return -100
    if(fx==gx and fy==gy):
        return 100
    else:
        return 0

In [53]:
def q(Q,sx,sy):
    s0=Q[0][sx][sy]
    s1=Q[1][sx][sy]
    s2=Q[2][sx][sy]
    s3=Q[3][sx][sy]
    return max(s1,s2,s3,s0)

In [54]:
def Bellman_Operator(Q=np.zeros((4,xsize,ysize))):
    for k in range(4):
        for i in range(1,xsize-1):
            for j in range(1,ysize-1):
                ins=(i,j)
                a=k
                Q[k][i][j]=rew(ins,a)+gamma*(tp(ins,a,(i-1,j))*q(Q,i-1,j)+tp(ins,a,(i,j-1))*q(Q,i,j-1)+tp(ins,a,(i,j+1))*q(Q,i,j+1)+tp(ins,a,(i+1,j))*q(Q,i+1,j))
    return Q

In [55]:
Q=Bellman_Operator()
print(Q)

[[[   0.       0.       0.       0.       0.       0.       0.   ]
  [   0.    -100.    -100.    -100.    -100.    -100.       0.   ]
  [   0.       0.     -50.       0.       0.       0.       0.   ]
  [   0.       0.       0.       0.       0.       0.       0.   ]
  [   0.       0.       0.     -50.       0.       0.       0.   ]
  [   0.       0.       0.       0.       0.       0.       0.   ]
  [   0.       0.       0.       0.       0.       0.       0.   ]]

 [[   0.       0.       0.       0.       0.       0.       0.   ]
  [   0.    -100.       0.     -50.       0.       0.       0.   ]
  [   0.    -100.       0.       0.       0.       0.       0.   ]
  [   0.    -100.       0.       0.     -50.       0.       0.   ]
  [   0.    -100.       0.       0.       0.       0.       0.   ]
  [   0.    -100.       0.       0.       0.       0.       0.   ]
  [   0.       0.       0.       0.       0.       0.       0.   ]]

 [[   0.       0.       0.       0.       0.       0.     

In [58]:
def Value_iteration():
    W=np.zeros((4,xsize,ysize))
    for i in range(200):
        W=Bellman_Operator(W)
    OP=np.zeros((xsize,ysize))
    for i in range(xsize):
        for j in range(ysize):
            m=max(W[0][i][j],W[1][i][j],W[2][i][j],W[3][i][j])
            if(m==W[0][i][j]):
                OP[i][j]=0
            elif(m==W[1][i][j]):
                OP[i][j]=1
            elif(m==W[2][i][j]):
                OP[i][j]=2
            else:
                OP[i][j]=3
    return W,OP

In [60]:
w,op=Value_iteration()
print(op)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 3. 3. 3. 3. 3. 0.]
 [0. 2. 2. 2. 3. 3. 0.]
 [0. 2. 3. 3. 3. 3. 0.]
 [0. 2. 2. 2. 2. 3. 0.]
 [0. 2. 2. 2. 2. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
