In [1]:
#Question 3

import numpy as np
import matplotlib.pyplot as plt

In [12]:
n = input("Enter dimension of grid")
x = input("Enter initial x coord. of intruder")
y = input("Enter initial y coord. of intruder")
k = input("Enter #bulbs to be switched ON at a time")

TypeError: 'int' object is not callable

In [3]:
n=int(n)

In [4]:
x=int(x)
y=int(y)
k=int(k)

In [5]:
def move(s,x,y):
        if(s=="left"):
             return x,y-1   
        elif(s=="right"):
             return x,y+1   
        elif(s=="up"):
             return x-1,y   
        elif(s=="down"):
             return x+1,y   

In [11]:
import random
k=6
input=1
while(input):
    k_pos=[]
    print("-------------------------------------")
    if(x==0 and y==0):
        li=["right","down"]
    elif(x==0 and y==n-1):
        li=["left","down"]
    elif(x==n-1 and y==0):
        li=["right","up"]
    elif(x==n-1 and y==n-1):
        li=["up","left"]
    elif(x==0):
        li=["down","left","right"]
    elif(y==0):
        li=["up","down","right"]
    elif(x==n-1):
        li=["up","left","right"]
    elif(y==n-1):
        li=["up","down","left"]
    else:
        li=["up","down","left","right"]
        
    ar=np.zeros((n,n))
    
    d=k
    while(d!=0):
        s1=np.random.randint(n)
        s2=np.random.randint(n)
        if(ar[s1][s2]!=1):
            ar[s1][s2]=1
            d=d-1
        
        
    #k_pos.sort()
    print("k bulbs switched ON, rest switched OFF")
        
    p=np.random.randint(len(li))
    
    x,y=move(li[p],x,y)
    
    if(ar[x][y]==1):
        ar[x][y]=3
        print("Intruder Found!!")
        input=0
    else:
        ar[x][y]=2
                
    print(ar)     

-------------------------------------
k bulbs switched ON, rest switched OFF
[[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 2.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 1.]]
-------------------------------------
k bulbs switched ON, rest switched OFF
[[0. 1. 0. 0. 0.]
 [0. 1. 0. 2. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1.]]
-------------------------------------
k bulbs switched ON, rest switched OFF
[[0. 1. 1. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0.]]
-------------------------------------
k bulbs switched ON, rest switched OFF
[[0. 0. 1. 1. 1.]
 [0. 2. 0. 0. 0.]
 [0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]]
-------------------------------------
k bulbs switched ON, rest switched OFF
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 1. 1. 0. 1.]]
-------------------------------------
k bulbs switched ON, rest switched OFF
Intruder Found!!
[[0. 0. 0. 1. 0.]
 [0. 3. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0